---
- name: Ensure firewalld is stopped and disabled
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution_major_version == "7"

- name:  Install iptables packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ iptables_pkgs }}"

